# Generated by Django 4.2.4 on 2023-08-16 10:22

from django.db import migrations, models
import social_media.models


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=social_media.models.user_dirctory_path),
        ),
    ]
